### PR TITLE
fixed Icon size

### PR DESCRIPTION
**Pull request by Findus23**
as a followup to https://github.com/piwik/piwik/pull/11093 we need to specify the size for icons which are larger than 16px.

### CODE REVIEW

**Comment by Findus23** [comment]
I guess the failing UI-test isn't because of my change.

**Comment by sgiehl** [comment]
Thanks. As that shouldn't break anything even without the merge of piwik/piwik#11093, I'll merge this one before.

**Comment by Findus23** [comment]
Could you please release a new version with this change?
Thanks

**Comment by sgiehl** [comment]
sure

**Pull request merged**
